"""Regression tests for ODIN's mechanical guarantees.

Standard library only (`unittest`), matching the toolkit's own constraint. Run with:

    python -m unittest discover -s tests -v
    python tests/test_odin.py

Each test protects a promise the skill makes in writing. If a promise cannot be
tested cheaply, that is stated rather than faked.
"""

import io
import json
import os
import shutil
import subprocess
import sys
import tarfile
import tempfile
import unittest
import zipfile
from pathlib import Path

TESTS_DIR = Path(__file__).resolve().parent
SCRIPTS = TESTS_DIR.parent / "scripts"
ODIN = SCRIPTS / "odin.py"
sys.path.insert(0, str(SCRIPTS))

from odin_lib import archives, classify, common, readme  # noqa: E402


# --------------------------------------------------------------------------
# helpers
# --------------------------------------------------------------------------

def run_odin(*args, artifacts=None):
    """Invoke the CLI the way an operator would. Returns (exit_code, parsed_json)."""
    cmd = [sys.executable, str(ODIN)] + list(args)
    if artifacts:
        cmd += ["--artifacts", str(artifacts)]
    env = dict(os.environ)
    env.pop("ODIN_ARTIFACT_ROOT", None)
    proc = subprocess.run(cmd, capture_output=True, text=True, env=env, timeout=300)
    try:
        payload = json.loads(proc.stdout)
    except json.JSONDecodeError:
        raise AssertionError(
            "odin.py %s produced non-JSON output\nstdout: %s\nstderr: %s"
            % (" ".join(args), proc.stdout[:2000], proc.stderr[:2000]))
    return proc.returncode, payload


def write(path, text):
    """Write UTF-8 with LF endings.

    write(Path, newline=...) is Python 3.10+, and this project targets 3.8.
    CI's 3.8 leg exists precisely to keep that claim honest.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as fh:
        fh.write(text)


def build_fixture(root: Path):
    """A small repository exercising the cases the inventory must handle."""
    (root / "src").mkdir(parents=True)
    (root / "tests").mkdir()
    (root / "node_modules" / "left-pad").mkdir(parents=True)

    write(root / "src" / "app.py", "#!/usr/bin/env python3\n"
        '"""Fixture entry point."""\n'
        "import os\n\n"
        "def run():\n"
        "    # TODO(fixture): unfinished on purpose\n"
        "    raise NotImplementedError\n")
    write(root / "src" / "generated.py", "# @generated by a fixture codegen - DO NOT EDIT\nVALUE = 1\n")
    write(root / "tests" / "test_app.py", "def test_noop():\n    assert True\n")
    write(root / "node_modules" / "left-pad" / "package.json", '{"name":"left-pad","version":"1.3.0"}\n')
    write(root / "package.json", '{"name":"fixture","version":"1.0.0"}\n')
    write(root / "README.md", "# Fixture\n")
    (root / "data.bin").write_bytes(bytes(range(256)) * 8)
    return root


PLANTED_SECRET = "AKIAIOSFODNN7EXAMPLE"
PLANTED_ENV_SECRET = "s3cr3t-Fixture-Value-9182734650"


class FixtureCase(unittest.TestCase):
    """Builds a fresh fixture repository and artifact root per test."""

    def setUp(self):
        self.tmp = Path(tempfile.mkdtemp(prefix="odin-test-"))
        self.repo = build_fixture(self.tmp / "repo")
        self.artifacts = self.tmp / "artifacts"

    def tearDown(self):
        shutil.rmtree(self.tmp, ignore_errors=True)

    def init(self, **kw):
        code, out = run_odin("init", "--repo", str(self.repo),
                             "--artifacts", str(self.artifacts),
                             "--network", kw.get("network", "denied"),
                             "--sandbox", kw.get("sandbox", "none"))
        self.assertEqual(code, 0, out)
        return out

    @property
    def packet(self):
        return self.artifacts / "findings"

    def tree_hashes(self, root: Path):
        out = {}
        for path in sorted(root.rglob("*")):
            if path.is_file() and not path.is_symlink():
                out[path.relative_to(root).as_posix()] = common.sha256_file(path)
        return out


# --------------------------------------------------------------------------
# promise 1: the repository is never modified
# --------------------------------------------------------------------------

class TestNonModification(FixtureCase):

    def test_full_run_leaves_the_repository_byte_identical(self):
        before = self.tree_hashes(self.repo)
        self.init()
        for cmd in ("env", "inventory", "todos", "secrets", "docstub"):
            code, out = run_odin(cmd, artifacts=self.artifacts)
            self.assertEqual(code, 0, (cmd, out))
        after = self.tree_hashes(self.repo)
        self.assertEqual(before, after,
                         "REPO_ROOT changed during analysis; it is evidence and must not be modified")

    def test_verify_reports_pass_on_an_untouched_repository(self):
        self.init()
        run_odin("inventory", artifacts=self.artifacts)
        code, out = run_odin("verify", artifacts=self.artifacts)
        self.assertEqual(code, 0, out)
        self.assertEqual(out["status"], "PASS", out)
        self.assertTrue(out["repository_unchanged"])

    def test_verify_detects_a_modified_file(self):
        self.init()
        run_odin("inventory", artifacts=self.artifacts)
        write(self.repo / "README.md", "# Fixture, tampered\n")
        code, out = run_odin("verify", artifacts=self.artifacts)
        self.assertEqual(out["status"], "FAIL", out)
        self.assertEqual(out["severity"], "critical-process-failure")
        self.assertIn("README.md", [m["path"] for m in out["content_modified"]])

    def test_verify_detects_an_added_and_a_removed_file(self):
        self.init()
        run_odin("inventory", artifacts=self.artifacts)
        write(self.repo / "NEW.txt", "new\n")
        (self.repo / "README.md").unlink()
        code, out = run_odin("verify", artifacts=self.artifacts)
        self.assertEqual(out["status"], "FAIL")
        self.assertIn("NEW.txt", out["added"])
        self.assertIn("README.md", out["removed"])

    def test_toolkit_writes_no_bytecode_into_the_repository(self):
        """The toolkit may live inside the repository it analyses.

        Importing odin_lib would normally drop __pycache__ next to the source,
        which the protocol forbids: caches must never be written into REPO_ROOT.
        """
        toolkit = self.repo / "vendored-skill" / "scripts"
        toolkit.parent.mkdir(parents=True, exist_ok=True)
        shutil.copytree(SCRIPTS, toolkit)
        for stale in toolkit.rglob("__pycache__"):
            shutil.rmtree(stale, ignore_errors=True)

        artifacts = self.tmp / "artifacts-vendored"
        proc = subprocess.run(
            [sys.executable, str(toolkit / "odin.py"), "init",
             "--repo", str(self.repo), "--artifacts", str(artifacts)],
            capture_output=True, text=True, timeout=300)
        self.assertEqual(proc.returncode, 0, proc.stdout + proc.stderr)

        polluted = sorted(str(p.relative_to(self.repo).as_posix())
                          for p in self.repo.rglob("__pycache__"))
        self.assertEqual(polluted, [],
                         "the toolkit wrote bytecode caches into REPO_ROOT: %r" % polluted)

    def test_artifact_root_inside_the_repository_is_refused(self):
        code, out = run_odin("init", "--repo", str(self.repo),
                             "--artifacts", str(self.repo / "findings-out"))
        self.assertNotEqual(code, 0)
        self.assertIn("outside REPO_ROOT", out.get("error", ""))
        self.assertFalse((self.repo / "findings-out").exists(),
                         "a refused init must not leave anything behind in REPO_ROOT")


# --------------------------------------------------------------------------
# promise 2: the run is deterministic
# --------------------------------------------------------------------------

class TestDeterminism(FixtureCase):

    def test_inventory_is_byte_identical_across_runs(self):
        self.init()
        run_odin("inventory", artifacts=self.artifacts)
        first = (self.packet / "inventory" / "files.jsonl").read_bytes()
        run_odin("inventory", artifacts=self.artifacts)
        second = (self.packet / "inventory" / "files.jsonl").read_bytes()
        self.assertEqual(first, second, "inventory output is not deterministic")

    def test_paths_are_ordered_bytewise_not_by_filesystem_order(self):
        self.init()
        run_odin("inventory", artifacts=self.artifacts)
        rows = [json.loads(l) for l in
                (self.packet / "inventory" / "files.jsonl").read_text(encoding="utf-8").splitlines() if l.strip()]
        paths = [r["path"] for r in rows]
        self.assertEqual(paths, sorted(paths, key=lambda p: p.encode("utf-8")))

    def test_scans_are_byte_identical_across_runs(self):
        self.init()
        run_odin("inventory", artifacts=self.artifacts)
        for cmd, rel in (("todos", "static-analysis/unfinished-work.json"),
                         ("secrets", "security/secrets-redacted.json")):
            run_odin(cmd, artifacts=self.artifacts)
            first = (self.packet / rel).read_bytes()
            run_odin(cmd, artifacts=self.artifacts)
            self.assertEqual(first, (self.packet / rel).read_bytes(),
                             "%s output is not deterministic" % cmd)

    def test_generated_json_uses_lf_and_sorted_keys(self):
        self.init()
        run_odin("inventory", artifacts=self.artifacts)
        raw = (self.packet / "inventory" / "roles.json").read_bytes()
        self.assertNotIn(b"\r\n", raw, "generated JSON must use LF line endings")
        obj = json.loads(raw)
        self.assertEqual(list(obj), sorted(obj), "generated JSON keys must be sorted")


# --------------------------------------------------------------------------
# promise 3: packaging is byte-reproducible
# --------------------------------------------------------------------------

class TestPackaging(FixtureCase):

    def _complete_packet(self):
        """Fill the packet enough that validation passes."""
        self.init()
        run_odin("inventory", artifacts=self.artifacts)
        run_odin("secrets", artifacts=self.artifacts)
        run_odin("docstub", artifacts=self.artifacts)
        P = self.packet
        for doc in common.REQUIRED_TOP_LEVEL_DOCS:
            if doc.endswith(".json"):
                continue
            write(P / doc, "# %s\n\nfixture\n" % doc)
        from odin_lib.verify import REQUIRED_PACKET_ARTIFACTS
        for rel in REQUIRED_PACKET_ARTIFACTS:
            target = P / rel
            if target.exists():
                continue
            target.parent.mkdir(parents=True, exist_ok=True)
            if rel.endswith(".mmd"):
                write(target, "graph TD\n  A --> B\n")
            elif rel.endswith(".jsonl"):
                write(target, '{"fixture": true}\n')
            elif rel.endswith((".json", ".sarif")):
                write(target, '{"fixture": true}\n')
            else:
                write(target, "# fixture\n")
        write(P / "tests" / "coverage-summary.json", '{"measured": false, "reason": "fixture"}\n')
        write(P / "inventory" / "modules.json", '{"modules": []}\n')
        # complete every stub
        for md in (P / "files").rglob("*.md"):
            text = md.read_text(encoding="utf-8")
            write(md, text.replace("<!-- odin:pending -->", "").replace("PENDING", "documented"))
        return P

    def test_packaging_the_same_content_twice_is_byte_identical(self):
        self._complete_packet()
        run_odin("verify", artifacts=self.artifacts)
        run_odin("validate", artifacts=self.artifacts)
        code, first = run_odin("package", artifacts=self.artifacts)
        self.assertEqual(first["status"], "PASS", first)
        code, second = run_odin("package", artifacts=self.artifacts)
        self.assertEqual(first["zip_sha256"], second["zip_sha256"],
                         "repackaging identical content must be byte-identical")

    def test_archive_members_carry_fixed_timestamps_and_modes(self):
        self._complete_packet()
        run_odin("verify", artifacts=self.artifacts)
        run_odin("validate", artifacts=self.artifacts)
        run_odin("package", artifacts=self.artifacts)
        with zipfile.ZipFile(self.artifacts / "findings.zip") as z:
            infos = z.infolist()
            self.assertTrue(infos)
            for info in infos:
                self.assertEqual(info.date_time, (1980, 1, 1, 0, 0, 0), info.filename)
            names = z.namelist()
            self.assertEqual(names, sorted(names, key=lambda n: n.encode("utf-8")),
                             "archive members must be in bytewise-sorted order")

    def test_manifest_covers_every_packet_file_except_itself(self):
        P = self._complete_packet()
        code, out = run_odin("manifest", artifacts=self.artifacts)
        self.assertEqual(out["verification"]["status"], "PASS", out)
        listed = {line.split("  ", 1)[1] for line in
                  (P / "MANIFEST.sha256").read_text(encoding="utf-8").splitlines() if line.strip()}
        self.assertNotIn("MANIFEST.sha256", listed)

    def test_manifest_verification_fails_when_a_file_changes(self):
        P = self._complete_packet()
        run_odin("manifest", artifacts=self.artifacts)
        write(P / "README.md", "# tampered\n")
        from odin_lib import package as packaging
        state = common.State.load(str(self.artifacts))
        result = packaging.verify_manifest(state)
        self.assertEqual(result["status"], "FAIL")
        self.assertIn("README.md", result["digest_mismatch"])


# --------------------------------------------------------------------------
# promise 4: no secret value reaches the packet
# --------------------------------------------------------------------------

class TestRedaction(FixtureCase):

    def setUp(self):
        super().setUp()
        write(self.repo / "config.py", 'AWS_KEY = "%s"\n' % PLANTED_SECRET)
        write(self.repo / ".env", "API_SECRET=%s\n" % PLANTED_ENV_SECRET)

    def test_planted_secrets_are_detected(self):
        self.init()
        run_odin("inventory", artifacts=self.artifacts)
        code, out = run_odin("secrets", artifacts=self.artifacts)
        self.assertGreaterEqual(out["findings_total"], 2, out)
        report = json.loads((self.packet / "security" / "secrets-redacted.json").read_text(encoding="utf-8"))
        paths = {f["path"] for f in report["findings"]}
        self.assertIn("config.py", paths)
        self.assertIn(".env", paths)

    def test_no_secret_value_appears_anywhere_in_the_packet(self):
        self.init()
        for cmd in ("env", "inventory", "todos", "secrets", "docstub"):
            run_odin(cmd, artifacts=self.artifacts)
        leaked = []
        for path in self.packet.rglob("*"):
            if not path.is_file():
                continue
            blob = path.read_bytes()
            for secret in (PLANTED_SECRET, PLANTED_ENV_SECRET):
                if secret.encode() in blob:
                    leaked.append((path.relative_to(self.packet).as_posix(), secret))
        self.assertEqual(leaked, [], "secret values leaked into the packet: %r" % leaked)

    def test_findings_record_redaction_not_values(self):
        self.init()
        run_odin("inventory", artifacts=self.artifacts)
        run_odin("secrets", artifacts=self.artifacts)
        report = json.loads((self.packet / "security" / "secrets-redacted.json").read_text(encoding="utf-8"))
        for finding in report["findings"]:
            self.assertEqual(finding["value"], "<REDACTED>")
            self.assertIn("fingerprint_sha256_16", finding)
            self.assertIn("not validated", finding["validation"])

    def test_fingerprints_are_stable_and_not_reversible(self):
        a = common.fingerprint(PLANTED_SECRET)
        b = common.fingerprint(PLANTED_SECRET)
        self.assertEqual(a, b, "fingerprints must be stable for deduplication")
        self.assertEqual(len(a), 16)
        self.assertNotIn(PLANTED_SECRET.lower(), a.lower())

    def test_packet_leak_audit_catches_a_planted_value(self):
        self.init()
        run_odin("inventory", artifacts=self.artifacts)
        run_odin("secrets", artifacts=self.artifacts)
        (self.packet / "tool-output" / "leak.log").parent.mkdir(parents=True, exist_ok=True)
        write(self.packet / "tool-output" / "leak.log", "accidentally logged %s\n" % PLANTED_SECRET)
        from odin_lib import scan
        state = common.State.load(str(self.artifacts))
        hits = scan.audit_packet_for_leaks(state)
        self.assertTrue(any(h["packet_path"] == "tool-output/leak.log" for h in hits),
                        "the packet leak audit must catch a value written into the packet")

    def test_example_files_are_not_flagged_as_active(self):
        write(self.repo / ".env.example", "API_SECRET=changeme\n")
        self.init()
        run_odin("inventory", artifacts=self.artifacts)
        run_odin("secrets", artifacts=self.artifacts)
        report = json.loads((self.packet / "security" / "secrets-redacted.json").read_text(encoding="utf-8"))
        for finding in report["findings"]:
            if finding["path"] == ".env.example":
                self.assertNotEqual(finding["status"], "active-looking")


# --------------------------------------------------------------------------
# promise 5: operator identity stays out of the packet
# --------------------------------------------------------------------------

class TestOperatorPrivacy(FixtureCase):

    def test_environment_report_withholds_path_home_and_temp_values(self):
        self.init()
        run_odin("env", artifacts=self.artifacts)
        report = json.loads((self.packet / "inventory" / "environment.json").read_text(encoding="utf-8"))
        env_vars = report["environment_variables_sanitized"]
        for name in ("PATH", "HOME", "USERPROFILE", "TEMP", "TMP"):
            if name in env_vars:
                self.assertTrue(env_vars[name].startswith("<REDACTED"),
                                "%s value must not be recorded: %r" % (name, env_vars[name]))

    def test_home_directory_string_does_not_appear_in_the_environment_report(self):
        self.init()
        run_odin("env", artifacts=self.artifacts)
        raw = (self.packet / "inventory" / "environment.json").read_text(encoding="utf-8")
        home = os.environ.get("USERPROFILE") or os.environ.get("HOME")
        if home and len(home) > 3:
            self.assertNotIn(home, raw,
                             "the operator's home directory must not appear in the packet")


# --------------------------------------------------------------------------
# inventory behaviour
# --------------------------------------------------------------------------

class TestInventory(FixtureCase):

    def test_ignored_and_vendored_content_is_still_inventoried(self):
        write(self.repo / ".gitignore", "node_modules/\ndata.bin\n")
        self.init()
        run_odin("inventory", artifacts=self.artifacts)
        rows = [json.loads(l) for l in
                (self.packet / "inventory" / "files.jsonl").read_text(encoding="utf-8").splitlines() if l.strip()]
        paths = {r["path"] for r in rows}
        self.assertIn("node_modules/left-pad/package.json", paths,
                      "filesystem traversal, not gitignore, defines the inventory")
        self.assertIn("data.bin", paths)

    def test_vendored_and_generated_content_is_classified(self):
        self.init()
        run_odin("inventory", artifacts=self.artifacts)
        rows = {r["path"]: r for r in
                (json.loads(l) for l in
                 (self.packet / "inventory" / "files.jsonl").read_text(encoding="utf-8").splitlines() if l.strip())}
        self.assertEqual(rows["node_modules/left-pad/package.json"]["origin_hint"], "vendored")
        self.assertEqual(rows["src/generated.py"]["origin_hint"], "generated")
        self.assertEqual(rows["src/app.py"]["origin_hint"], "first-party")
        self.assertEqual(rows["tests/test_app.py"]["role_hint"], "test")

    def test_every_regular_file_gets_exactly_one_document_path(self):
        self.init()
        run_odin("inventory", artifacts=self.artifacts)
        code, out = run_odin("docstub", artifacts=self.artifacts)
        rows = [json.loads(l) for l in
                (self.packet / "inventory" / "files.jsonl").read_text(encoding="utf-8").splitlines() if l.strip()]
        regular = [r for r in rows if r["entry_type"] == "regular-file"]
        self.assertEqual(out["stubs_written"], len(regular))
        self.assertEqual(len({r["doc_path"] for r in regular}), len(regular),
                         "document paths must be unique")
        for r in regular:
            self.assertTrue((self.packet / r["doc_path"]).is_file(), r["path"])

    def test_binary_content_is_detected(self):
        self.init()
        run_odin("inventory", artifacts=self.artifacts)
        rows = {r["path"]: r for r in
                (json.loads(l) for l in
                 (self.packet / "inventory" / "files.jsonl").read_text(encoding="utf-8").splitlines() if l.strip())}
        self.assertEqual(rows["data.bin"]["content_kind"], "binary")
        self.assertEqual(rows["src/app.py"]["content_kind"], "text")


class TestWindowsReservedPaths(unittest.TestCase):
    """Document paths must survive names the host filesystem cannot represent."""

    def test_reserved_device_names_are_escaped(self):
        doc, remapped = common.safe_doc_path("src/aux.c")
        self.assertTrue(remapped)
        self.assertNotIn("/aux.c.md", doc)

    def test_forbidden_characters_are_escaped(self):
        doc, remapped = common.safe_doc_path('weird/na:me?.txt')
        self.assertTrue(remapped)
        for ch in ':?':
            self.assertNotIn(ch, doc.split("files/", 1)[1])

    def test_ordinary_paths_are_untouched(self):
        doc, remapped = common.safe_doc_path("src/core/parser.py")
        self.assertFalse(remapped)
        self.assertEqual(doc, "files/src/core/parser.py.md")

    def test_mapping_stays_injective(self):
        seen = {}
        for path in ("src/aux.c", "src/_aux.c", "src/aux.c.md", "a/con.txt", "a/_con.txt"):
            doc, _ = common.safe_doc_path(path)
            self.assertNotIn(doc, seen, "collision between %r and %r" % (path, seen.get(doc)))
            seen[doc] = path


# --------------------------------------------------------------------------
# the ARCHIVE RULE
# --------------------------------------------------------------------------

class TestArchiveInspection(unittest.TestCase):

    def setUp(self):
        self.tmp = Path(tempfile.mkdtemp(prefix="odin-arc-"))

    def tearDown(self):
        shutil.rmtree(self.tmp, ignore_errors=True)

    def test_zip_member_table_is_read_without_extraction(self):
        target = self.tmp / "sample.zip"
        with zipfile.ZipFile(target, "w") as z:
            z.writestr("a.txt", "alpha")
            z.writestr("dir/b.txt", "beta")
        report = archives.inspect(target, "zip", "sample.zip")
        self.assertEqual(report["status"], "inspected")
        self.assertFalse(report["extracted"])
        self.assertEqual(report["counts"]["members"], 2)
        self.assertEqual({m["name"] for m in report["members"]}, {"a.txt", "dir/b.txt"})
        # nothing was written next to the archive
        self.assertEqual(sorted(p.name for p in self.tmp.iterdir()), ["sample.zip"])

    def test_path_traversal_member_is_detected(self):
        target = self.tmp / "evil.zip"
        with zipfile.ZipFile(target, "w") as z:
            z.writestr("../../etc/passwd", "x")
            z.writestr("ok.txt", "y")
        report = archives.inspect(target, "zip", "evil.zip")
        self.assertEqual(report["counts"]["traversing_paths"], 1)
        self.assertIn("path-traversal", [f["kind"] for f in report["findings"]])

    def test_absolute_path_member_is_detected(self):
        target = self.tmp / "abs.zip"
        with zipfile.ZipFile(target, "w") as z:
            z.writestr("/etc/shadow", "x")
        report = archives.inspect(target, "zip", "abs.zip")
        self.assertEqual(report["counts"]["traversing_paths"], 1)

    def test_symlink_escape_in_tar_is_detected(self):
        target = self.tmp / "link.tar"
        with tarfile.open(target, "w") as t:
            info = tarfile.TarInfo("inner/link")
            info.type = tarfile.SYMTYPE
            info.linkname = "../../../../etc/passwd"
            t.addfile(info)
        report = archives.inspect(target, "tar", "link.tar")
        self.assertEqual(report["counts"]["escaping_links"], 1)
        self.assertIn("symlink-escape", [f["kind"] for f in report["findings"]])

    def test_benign_relative_symlink_is_not_flagged(self):
        target = self.tmp / "ok.tar"
        with tarfile.open(target, "w") as t:
            info = tarfile.TarInfo("dir/link")
            info.type = tarfile.SYMTYPE
            info.linkname = "target.txt"
            t.addfile(info)
        report = archives.inspect(target, "tar", "ok.tar")
        self.assertEqual(report["counts"]["escaping_links"], 0)

    def test_decompression_bomb_ratio_is_flagged(self):
        target = self.tmp / "bomb.zip"
        with zipfile.ZipFile(target, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as z:
            z.writestr("big.txt", "A" * 5_000_000)
        report = archives.inspect(target, "zip", "bomb.zip")
        kinds = [f["kind"] for f in report["findings"]]
        self.assertIn("decompression-bomb-candidate", kinds)

    def test_nested_archive_is_flagged_and_not_opened(self):
        inner = io.BytesIO()
        with zipfile.ZipFile(inner, "w") as z:
            z.writestr("deep.txt", "deep")
        target = self.tmp / "outer.zip"
        with zipfile.ZipFile(target, "w") as z:
            z.writestr("inner.zip", inner.getvalue())
        report = archives.inspect(target, "zip", "outer.zip")
        self.assertEqual(report["counts"]["nested_archives"], 1)
        self.assertIn("nested-archive", [f["kind"] for f in report["findings"]])

    def test_malformed_archive_is_reported_not_raised(self):
        target = self.tmp / "broken.zip"
        target.write_bytes(b"PK\x03\x04" + b"\x00" * 64)
        report = archives.inspect(target, "zip", "broken.zip")
        self.assertIn(report["status"], ("malformed", "not-an-archive"))
        self.assertIn("error", report)

    def test_archive_kind_detection(self):
        self.assertEqual(archives.archive_kind("x.whl", None), "zip")
        self.assertEqual(archives.archive_kind("x.tar.gz", None), "tar")
        self.assertEqual(archives.archive_kind("x.jar", None), "zip")
        self.assertIsNone(archives.archive_kind("x.txt", None))
        self.assertIsNone(archives.archive_kind("x.gz", "gzip stream"))


class TestArchiveInventoryIntegration(FixtureCase):

    def test_repository_archive_is_inspected_during_inventory(self):
        with zipfile.ZipFile(self.repo / "bundle.zip", "w") as z:
            z.writestr("inside.txt", "hello")
            z.writestr("../escape.txt", "bad")
        self.init()
        run_odin("inventory", artifacts=self.artifacts)
        report = json.loads((self.packet / "inventory" / "archives.json").read_text(encoding="utf-8"))
        self.assertEqual(report["archives_found"], 1)
        entry = report["archives"][0]
        self.assertEqual(entry["path"], "bundle.zip")
        self.assertEqual(entry["counts"]["members"], 2)
        self.assertIn("path-traversal", [f["kind"] for f in entry["findings"]])
        self.assertFalse(entry["extracted"])
        rows = {r["path"]: r for r in
                (json.loads(l) for l in
                 (self.packet / "inventory" / "files.jsonl").read_text(encoding="utf-8").splitlines() if l.strip())}
        self.assertEqual(rows["bundle.zip"]["archive"]["members"], 2)

    def test_archive_members_do_not_become_repository_files(self):
        with zipfile.ZipFile(self.repo / "bundle.zip", "w") as z:
            z.writestr("inside.txt", "hello")
        self.init()
        run_odin("inventory", artifacts=self.artifacts)
        rows = [json.loads(l) for l in
                (self.packet / "inventory" / "files.jsonl").read_text(encoding="utf-8").splitlines() if l.strip()]
        paths = {r["path"] for r in rows}
        self.assertIn("bundle.zip", paths)
        self.assertNotIn("inside.txt", paths,
                         "archive members are embedded artifacts, not repository files")


# --------------------------------------------------------------------------
# measured coverage
# --------------------------------------------------------------------------

class TestCoverage(FixtureCase):

    def test_coverage_help_works(self):
        proc = subprocess.run(
            [sys.executable, str(ODIN), "coverage", "--help"],
            capture_output=True, text=True, timeout=30)
        self.assertEqual(proc.returncode, 0, proc.stderr)
        self.assertIn("stdlib trace", proc.stdout)

    def test_coverage_is_policy_blocked_without_a_sandbox(self):
        before = self.tree_hashes(self.repo)
        self.init(sandbox="none")
        code, out = run_odin(
            "coverage", "--artifacts", str(self.artifacts), "src/app.py")
        self.assertEqual(code, 0, out)
        self.assertEqual(out["status"], "blocked_by_policy")

        summary = json.loads(
            (self.packet / "tests" / "coverage-summary.json").read_text(encoding="utf-8"))
        self.assertIs(summary["measured"], False)
        self.assertNotIn("line_percent", summary)
        manifest = json.loads(
            (self.packet / "ACTION_MANIFEST.json").read_text(encoding="utf-8"))
        self.assertEqual(manifest["actions"][-1]["status"], "blocked_by_policy")
        self.assertIs(manifest["actions"][-1]["repo_code_executed"], False)
        self.assertEqual(before, self.tree_hashes(self.repo))

        from odin_lib import verify
        state = common.State.load(str(self.artifacts))
        self.assertEqual(verify.validate(state)["coverage_claims"]["status"], "ok")

    def test_declared_sandbox_produces_measured_line_coverage(self):
        write(self.repo / "tests" / "test_app.py",
              "import unittest\n\n"
              "class PassingTest(unittest.TestCase):\n"
              "    def test_true(self):\n"
              "        self.assertTrue(True)\n")
        before = self.tree_hashes(self.repo)
        self.init(sandbox="platform-sandbox fixture")
        code, out = run_odin(
            "coverage", "--artifacts", str(self.artifacts),
            "--module", "unittest", "discover", "-s", "tests")
        self.assertEqual(code, 0, out)
        self.assertEqual(out["status"], "measured")
        self.assertIs(out["measured"], True)
        self.assertGreater(out["line_total"], 0)
        self.assertGreaterEqual(out["line_percent"], 0.0)
        self.assertLessEqual(out["line_percent"], 100.0)
        self.assertTrue(out["files"])
        self.assertEqual(out["target"], {"kind": "module", "value": "unittest"})
        self.assertTrue(any((self.packet / rel).is_file()
                            for rel in out["native_artifacts"]))
        self.assertEqual(before, self.tree_hashes(self.repo))

        manifest = json.loads(
            (self.packet / "ACTION_MANIFEST.json").read_text(encoding="utf-8"))
        self.assertEqual(manifest["actions"][-1]["status"], "succeeded")
        self.assertIs(manifest["actions"][-1]["repo_code_executed"], True)


# --------------------------------------------------------------------------
# validation honesty
# --------------------------------------------------------------------------

class TestValidation(FixtureCase):

    def test_validation_fails_on_an_empty_packet(self):
        self.init()
        run_odin("inventory", artifacts=self.artifacts)
        code, out = run_odin("validate", artifacts=self.artifacts)
        self.assertEqual(code, 1)
        self.assertEqual(out["status"], "FAIL")
        self.assertTrue(out["blocking_problems"])

    def test_validation_fails_while_document_stubs_remain(self):
        self.init()
        run_odin("inventory", artifacts=self.artifacts)
        run_odin("docstub", artifacts=self.artifacts)
        code, out = run_odin("validate", artifacts=self.artifacts)
        self.assertTrue(
            any("stub" in p for p in out["blocking_problems"]),
            "unfilled stubs must block packaging: %r" % out["blocking_problems"])

    def test_unmeasured_coverage_may_not_carry_a_percentage(self):
        self.init()
        run_odin("inventory", artifacts=self.artifacts)
        (self.packet / "tests").mkdir(parents=True, exist_ok=True)
        write(self.packet / "tests" / "coverage-summary.json", '{"measured": false, "line_percent": 92.4}\n')
        from odin_lib import verify
        state = common.State.load(str(self.artifacts))
        report = verify.validate(state)
        self.assertEqual(report["coverage_claims"]["status"], "contradiction")

    def test_missing_measured_field_is_invalid(self):
        self.init()
        run_odin("inventory", artifacts=self.artifacts)
        (self.packet / "tests").mkdir(parents=True, exist_ok=True)
        write(self.packet / "tests" / "coverage-summary.json", '{"line_percent": 92.4}\n')
        from odin_lib import verify
        state = common.State.load(str(self.artifacts))
        report = verify.validate(state)
        self.assertEqual(report["coverage_claims"]["status"], "invalid")

    def test_measured_coverage_needs_a_numeric_figure(self):
        self.init()
        run_odin("inventory", artifacts=self.artifacts)
        (self.packet / "tests").mkdir(parents=True, exist_ok=True)
        write(self.packet / "tests" / "coverage-summary.json", '{"measured": true}\n')
        from odin_lib import verify
        state = common.State.load(str(self.artifacts))
        report = verify.validate(state)
        self.assertEqual(report["coverage_claims"]["status"], "invalid")


# --------------------------------------------------------------------------
# action manifest
# --------------------------------------------------------------------------

class TestActionManifest(FixtureCase):

    def test_sequence_numbers_are_monotonic_and_unique(self):
        self.init()
        for i in range(4):
            code, out = run_odin("log", "--phase", "test", "--action-id", "A%d" % i,
                                 "--status", "succeeded", "--tool", "t",
                                 "--command", "c", artifacts=self.artifacts)
            self.assertEqual(code, 0, out)
        manifest = json.loads((self.packet / "ACTION_MANIFEST.json").read_text(encoding="utf-8"))
        seqs = [a["seq"] for a in manifest["actions"]]
        self.assertEqual(seqs, sorted(seqs))
        self.assertEqual(len(set(seqs)), len(seqs))

    def test_non_success_statuses_are_recorded(self):
        self.init()
        for status in ("failed", "skipped", "unavailable", "blocked_by_policy", "timeout"):
            run_odin("log", "--phase", "p", "--action-id", "X-" + status,
                     "--status", status, "--tool", "t", "--command", "c",
                     "--reason", "fixture", artifacts=self.artifacts)
        manifest = json.loads((self.packet / "ACTION_MANIFEST.json").read_text(encoding="utf-8"))
        recorded = {a["status"] for a in manifest["actions"]}
        for status in ("failed", "skipped", "unavailable", "blocked_by_policy", "timeout"):
            self.assertIn(status, recorded)

    def test_manifest_contains_no_wall_clock_timestamp(self):
        self.init()
        run_odin("log", "--phase", "p", "--action-id", "A", "--status", "succeeded",
                 "--tool", "t", "--command", "c", artifacts=self.artifacts)
        manifest = json.loads((self.packet / "ACTION_MANIFEST.json").read_text(encoding="utf-8"))
        for action in manifest["actions"]:
            self.assertNotIn("timestamp", action)
            self.assertNotIn("time", action)


# --------------------------------------------------------------------------
# classification
# --------------------------------------------------------------------------

class TestClassification(unittest.TestCase):

    def test_modern_language_extensions(self):
        expected = {
            "agda": "Agda",
            "bal": "Ballerina",
            "bend": "Bend",
            "chpl": "Chapel",
            "fnl": "Fennel",
            "fut": "Futhark",
            "gleam": "Gleam",
            "gr": "Grain",
            "idr": "Idris",
            "janet": "Janet",
            "lean": "Lean",
            "ml4": "OCaml Camlp4 syntax extension",
            "mojo": "Mojo",
            "odin": "Odin",
            "pony": "Pony",
            "roc": "Roc",
            "sml": "Standard ML",
            "spec": "RPM spec",
            "vale": "Vale",
            "wat": "WebAssembly text",
        }
        for extension, label in expected.items():
            with self.subTest(extension=extension):
                self.assertEqual(
                    classify.classify_extension("fixture." + extension),
                    (extension, label))

        self.assertEqual(classify.classify_extension("fixture.hx"), ("hx", "Haxe"))
        self.assertEqual(classify.classify_extension("fixture.rkt"), ("rkt", "Racket"))

    def test_shebang_beats_extension(self):
        self.assertEqual(classify.detect_shebang(b"#!/usr/bin/env python3\n")[1], "Python")
        self.assertEqual(classify.detect_shebang(b"#!/bin/bash\n")[1], "Bash")
        self.assertIsNone(classify.detect_shebang(b"import os\n"))

    def test_magic_detection(self):
        self.assertEqual(classify.detect_magic(b"\x89PNG\r\n\x1a\n")[0], "PNG image")
        self.assertEqual(classify.detect_magic(b"PK\x03\x04rest")[0],
                         "ZIP container (zip/jar/whl/docx/xlsx/apk/...)")
        self.assertIsNone(classify.detect_magic(b"plain text"))

    def test_env_example_is_not_sensitive_but_env_is(self):
        self.assertTrue(any(p.search(".env") for p in classify.SENSITIVE_NAME_PATTERNS))
        self.assertFalse(any(p.search(".env.example") for p in classify.SENSITIVE_NAME_PATTERNS))

    def test_source_language_detection(self):
        self.assertTrue(classify.is_source_language("Python"))
        self.assertTrue(classify.is_source_language("Rust"))
        self.assertFalse(classify.is_source_language("Markdown"))
        self.assertFalse(classify.is_source_language("PNG image"))
        self.assertFalse(classify.is_source_language(None))


# --------------------------------------------------------------------------
# repository README generation support
# --------------------------------------------------------------------------

GOOD_README = """# Project

## The Rundown

- does a thing
- built with Python

## Last Updated

2026-09-15

## Table of Contents

- [The Rundown](#the-rundown)
- [Tech Stack and Dependencies](#tech-stack-and-dependencies)
- [Change Log](#change-log)

## Repository Overview
## Components
## Architecture Overview
## Tech Stack and Dependencies
## Project Layout
## Getting Started (Local Development)
## Configuration
## Running the System
## Deployment and CI/CD
## Deep Code Reference
## Data and Integrations
## Security Notes
## Observability and Monitoring
## Common Tasks and Troubleshooting
## Change Log
## Contributing
## License
"""


class TestReadmeLint(unittest.TestCase):

    """The formatting constraints exist because they break real renderers."""

    EMOJI = chr(0x1F680)
    BOX_DRAWING = [chr(0x2500), chr(0x2514), chr(0x251C)]
    ARROW = chr(0x2192)
    GEOMETRIC = chr(0x25A0)
    TECHNICAL = chr(0x23F0)

    def test_a_conforming_readme_passes(self):
        report = readme.lint(GOOD_README)
        self.assertEqual(report["status"], "PASS", report["violations"])

    def test_emoji_in_heading_is_an_error(self):
        body = "## " + self.EMOJI + " Getting Started" + chr(10)
        report = readme.lint(body, require_sections=False)
        self.assertEqual(report["status"], "FAIL")
        self.assertIn("emoji-in-heading", [v["rule"] for v in report["violations"]])

    def test_emoji_shortcode_in_heading_is_an_error(self):
        report = readme.lint("## :rocket: Getting Started" + chr(10),
                             require_sections=False)
        self.assertIn("emoji-shortcode-in-heading",
                      [v["rule"] for v in report["violations"]])

    def test_ampersand_in_heading_is_an_error(self):
        report = readme.lint("## Tech Stack & Dependencies" + chr(10),
                             require_sections=False)
        self.assertEqual(report["status"], "FAIL")
        self.assertIn("ampersand-in-heading", [v["rule"] for v in report["violations"]])

    def test_em_and_en_dash_are_rejected(self):
        for ch in (chr(0x2014), chr(0x2013)):
            report = readme.lint("Human prose " + ch + " nope" + chr(10),
                                 require_sections=False)
            self.assertIn("prose-dash", [v["rule"] for v in report["violations"]])

    def test_box_drawing_characters_are_rejected(self):
        for ch in self.BOX_DRAWING:
            report = readme.lint("text " + ch + " more" + chr(10),
                                 require_sections=False)
            self.assertIn("forbidden-unicode", [v["rule"] for v in report["violations"]],
                          "box-drawing U+%04X must be rejected" % ord(ch))

    def test_arrow_characters_are_rejected(self):
        report = readme.lint("A " + self.ARROW + " B" + chr(10), require_sections=False)
        self.assertIn("forbidden-unicode", [v["rule"] for v in report["violations"]])

    def test_geometric_and_technical_ranges_are_rejected(self):
        for ch in (self.GEOMETRIC, self.TECHNICAL):
            report = readme.lint("x " + ch + chr(10), require_sections=False)
            self.assertIn("forbidden-unicode", [v["rule"] for v in report["violations"]],
                          "U+%04X must be rejected" % ord(ch))

    def test_forbidden_unicode_is_caught_inside_code_fences(self):
        body = "```" + chr(10) + "src " + chr(0x2514) + chr(0x2500) + " file" + chr(10) + "```" + chr(10)
        report = readme.lint(body, require_sections=False)
        self.assertIn("forbidden-unicode", [v["rule"] for v in report["violations"]],
                      "a fenced block is still rendered; it must be checked too")

    def test_ascii_replacements_are_accepted(self):
        body = chr(10).join([
            "A --> B", "", "+------+", "| box  |", "+------+", "",
            "  - dir/", "    - file.cs", ""])
        report = readme.lint(body, require_sections=False)
        self.assertEqual(report["status"], "PASS", report["violations"])

    def test_broken_toc_anchor_is_an_error(self):
        body = chr(10).join(["## Getting Started", "", "- [Nope](#does-not-exist)", ""])
        report = readme.lint(body, require_sections=False)
        self.assertIn("broken-toc-anchor", [v["rule"] for v in report["violations"]])

    def test_valid_toc_anchor_resolves(self):
        body = chr(10).join(["## Getting Started", "", "- [Go](#getting-started)", ""])
        report = readme.lint(body, require_sections=False)
        self.assertNotIn("broken-toc-anchor", [v["rule"] for v in report["violations"]])

    def test_toc_anchor_slugs_match_github_rules(self):
        self.assertEqual(readme.slugify("Getting Started (Local Development)"),
                         "getting-started-local-development")
        self.assertEqual(readme.slugify("Tech Stack and Dependencies"),
                         "tech-stack-and-dependencies")
        self.assertEqual(readme.slugify("Deployment and CI/CD"), "deployment-and-cicd")

    def test_missing_required_sections_are_reported(self):
        report = readme.lint("# Title" + chr(10) + chr(10) + "## Overview" + chr(10))
        self.assertEqual(report["status"], "FAIL")
        self.assertIn("The Rundown", report["missing_required_sections"])

    def test_rundown_must_come_first(self):
        body = GOOD_README.replace("## The Rundown", "## Zzz Later", 1)
        body += chr(10) + "## The Rundown" + chr(10) + chr(10) + "- late" + chr(10)
        report = readme.lint(body)
        self.assertIn("section-order", [v["rule"] for v in report["violations"]])


class TestReadmeScan(FixtureCase):

    def test_scan_detects_added_ecosystem_manifests(self):
        fixtures = {
            "zig": ["build.zig", "build.zig.zon"],
            "haskell": ["stack.yaml", "fixture.cabal", "cabal.project"],
            "ocaml": ["dune-project", "fixture.opam"],
            "nix": ["flake.nix", "default.nix", "shell.nix"],
            "terraform": ["main.tf", ".terraform.lock.hcl"],
            "bazel": ["BUILD", "BUILD.bazel", "WORKSPACE", "WORKSPACE.bazel",
                      "MODULE.bazel"],
            "julia": ["Project.toml", "Manifest.toml"],
            "r": ["DESCRIPTION", "renv.lock"],
        }
        expected_evidence = {}
        for ecosystem, names in fixtures.items():
            expected_evidence[ecosystem] = []
            for name in names:
                path = Path("ecosystems") / ecosystem / name
                write(self.repo / path, "fixture\n")
                expected_evidence[ecosystem].append(path.as_posix())

        self.init()
        run_odin("inventory", artifacts=self.artifacts)
        code, out = run_odin("readme-scan", artifacts=self.artifacts)
        self.assertEqual(code, 0, out)
        report = json.loads(
            (self.packet / "readme" / "component-map.json").read_text(encoding="utf-8"))
        detected = report["ecosystems_detected"]
        for ecosystem, evidence in expected_evidence.items():
            with self.subTest(ecosystem=ecosystem):
                self.assertIn(ecosystem, detected)
                self.assertCountEqual(detected[ecosystem]["evidence"], evidence)

    def test_scan_ranks_languages_and_finds_manifests(self):
        self.init()
        run_odin("inventory", artifacts=self.artifacts)
        code, out = run_odin("readme-scan", artifacts=self.artifacts)
        self.assertEqual(code, 0, out)
        report = json.loads(
            (self.packet / "readme" / "component-map.json").read_text(encoding="utf-8"))
        self.assertIn("node", report["ecosystems_detected"])
        self.assertIn("package.json", report["manifests_and_lockfiles"])
        self.assertTrue(report["languages_ranked"])

    def test_scan_reports_absences_as_evidence(self):
        self.init()
        run_odin("inventory", artifacts=self.artifacts)
        run_odin("readme-scan", artifacts=self.artifacts)
        report = json.loads(
            (self.packet / "readme" / "component-map.json").read_text(encoding="utf-8"))
        self.assertTrue(report["absences"]["no_ci"],
                        "a fixture with no CI must report the absence, not omit it")

    def test_scan_finds_dotnet_manifests_despite_source_role(self):
        """Regression: .sln/.csproj/Directory.Build.props are classified as
        first-party source, so a role_hint-only query reported no_manifests=true
        for a repository full of .NET manifests."""
        write(self.repo / "App.sln", "Microsoft Visual Studio Solution File\n")
        write(self.repo / "src" / "App" / "App.csproj", "<Project />\n")
        write(self.repo / "Directory.Build.props", "<Project />\n")
        write(self.repo / "global.json", "{}\n")
        self.init()
        run_odin("inventory", artifacts=self.artifacts)
        run_odin("readme-scan", artifacts=self.artifacts)
        report = json.loads(
            (self.packet / "readme" / "component-map.json").read_text(encoding="utf-8"))
        manifests = report["manifests_and_lockfiles"]
        for expected in ("App.sln", "src/App/App.csproj",
                         "Directory.Build.props", "global.json"):
            with self.subTest(manifest=expected):
                self.assertIn(expected, manifests)
        self.assertFalse(report["absences"]["no_manifests"])

    def test_scan_excludes_vendored_and_vcs_content(self):
        self.init()
        run_odin("inventory", artifacts=self.artifacts)
        run_odin("readme-scan", artifacts=self.artifacts)
        report = json.loads(
            (self.packet / "readme" / "component-map.json").read_text(encoding="utf-8"))
        self.assertNotIn("node_modules/left-pad/package.json",
                         report["manifests_and_lockfiles"])


if __name__ == "__main__":
    unittest.main(verbosity=2)
